make:
	g++ -o swept_surface swept_surface.cpp data.cpp cross_section.cpp control_point.cpp mesh.cpp face.cpp trackball.cpp camera.cpp -lm -lGL -lGLU -lglut

run:
	./swept_surface coke_bottle.txt

clean:
	rm ./swept_surface
